# Site settings
title: Jon Hillery
email: hillery@math.ucla.edu
description: > # this means to ignore newlines until "baseurl:"
   Mathematics PhD Student at UCLA. I'm interested in groups and their representations.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.domoritz.de" # the base hostname & protocol for your site
production_url: "https://www.domoritz.de"
github_username: jonhillery
permalink: /blog/:year/:month/:title.html

twitter:
  username: jonhillery

sass:
  style: compressed

collections:
  publications:
    output: false

jekyll-mentions:
  base_url: https://twitter.com

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-mentions
